apiVersion: apps/v1
kind: Deployment
metadata:
  name: enigmi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfingegram
      service: enigmi
  template: 
    metadata:
      labels:
        app: sfingegram
        service: enigmi
    spec:
      containers:
      - name: enigmi-container
        image: sfingegram/enigmi-service
        ports:
        - containerPort: 8080
        readinessProbe: 
          httpGet: 
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connessioni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfingegram
      service: connessioni
  template: 
    metadata:
      labels:
        app: sfingegram
        service: connessioni
    spec:
      containers:
      - name: connessioni-container
        image: sfingegram/connessioni-service
        env: 
        - name: SPRING_PROFILES_ACTIVE
          value: connessioni
        ports:
        - containerPort: 8080
        readinessProbe: 
          httpGet: 
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enigmiseguiti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfingegram
      service: enigmiseguiti
  template: 
    metadata:
      labels:
        app: sfingegram
        service: enigmiseguiti
    spec:
      containers:
      - name: enigmiseguiti-container
        image: sfingegram/enigmi-seguiti-service
        env: 
        - name: SPRING_PROFILES_ACTIVE
          value: enigmiseguiti
        ports:
        - containerPort: 8080
        readinessProbe: 
          httpGet: 
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfingegram
      service: apigateway
  template: 
    metadata:
      labels:
        app: sfingegram
        service: apigateway
    spec:
      containers:
      - name: apigateway-container
        image: sfingegram/api-gateway-service
        ports:
        - containerPort: 8080
        readinessProbe: 
          httpGet: 
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: enigmi
spec:
  selector:
    app: sfingegram
    service: enigmi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  
---
apiVersion: v1
kind: Service
metadata:
  name: connessioni
spec:
  selector:
    app: sfingegram
    service: connessioni
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: enigmiseguiti
spec:
  selector:
    app: sfingegram
    service: enigmiseguiti
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: sfingegram
    service: apigateway
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
#    nodePort: 32082
###################
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enigmi
spec:
  rules:
  - host: enigmi 
    http: 
      paths: 
      - pathType: Prefix
        path: /
        backend: 
          service: 
            name: apigateway
            port: 
              number: 8080 
  
---
###################
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-discovery-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-discovery-reader-binding
subjects:
# all service accounts in any namespace
- kind: Group
  name: system:serviceaccounts
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: service-discovery-reader
  apiGroup: ""

